theme: jekyll-theme-minimal
title: Amin MamandiPoor
logo: meAmin.jpg
description: >
  Email: amin.mamandi [at] ku [dot] edu
  LinkedIN: [profile](test.com)
  <br>
show_downloads: false
github:
  is_user_page: false
